[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
epochs = "epoZLPTE49aXQ5WLem3W3Jr2thfVgZWFJwkRJZGBsfS"

[programs.localnet]
epochs = "epoZLPTE49aXQ5WLem3W3Jr2thfVgZWFJwkRJZGBsfS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/amilz/.config/solana/id.json"

[scripts]
init_idl = "anchor idl init epoZLPTE49aXQ5WLem3W3Jr2thfVgZWFJwkRJZGBsfS --filepath target/idl/epochs.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create_collection = "ts-node scripts/initCollection.ts"
get_owner_assets = "ts-node scripts/getEpochsByOwner.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "AssetGtQBTSgm5s91d1RAQod5JmaZiJDxqsgtqrZud73"
program = "./tests/genesis/asset_0.2.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
slots_per_epoch = "32"
warp_slot = "18464"
deactivate_feature = "GDH5TVdbTPUpRnXaRyQqiKUa7uZAbZ28Q2N9bhbKoMLm"