[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bmp = "7s3va6xk3MHzL3rpqdxoVZKiNWdWcMEHgGi9FeFv1g8R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
