[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bmp = "7s3va6xk3MHzL3rpqdxoVZKiNWdWcMEHgGi9FeFv1g8R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/amilz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_idl = "anchor idl init 7s3va6xk3MHzL3rpqdxoVZKiNWdWcMEHgGi9FeFv1g8R --filepath target/idl/bmp.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
slots_per_epoch = "32"

[test]
startup_wait = 10000

[[test.genesis]]
address = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"
program = "./tests/genesis/wns.so"

[[test.validator.account]]
address = "9SUrE3EPBoXVjNywEDHSJKJdxebs8H8sLgEWdueEvnKX"
filename = "./tests/genesis/manager.json"
