[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
epochs = "epochsiFg8ornJS22urHE3jgveYuFydxPC79tdcbYc8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/amilz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_idl = "anchor idl init epochsiFg8ornJS22urHE3jgveYuFydxPC79tdcbYc8 --filepath target/idl/epochs.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
slots_per_epoch = "32"
warp_slot = "18464"
# MAKE SURE TO UPDATE TESTS WHEN UPDATING THIS

[test]
startup_wait = 10000

[[test.genesis]]
address = "AssetGtQBTSgm5s91d1RAQod5JmaZiJDxqsgtqrZud73"
program = "./tests/genesis/asset_program.so"

[workspace]
types = "api/utils/idl/"